### ISSUE TITLE
emogrifier usage?

### ISSUE THREAD

**Issue by dereuromark** [bigfishtv/cakephp-inline-style#1]
I think emogrifier is a bit more powerfu.
But I could be wrong.

Are there any test cases yet to compare those two?

By the way:
I used https://github.com/dereuromark/cakephp-tools/blob/2.x/Lib/InlineCssLib.php so far.

**Comment by ifunk** [comment]
I haven't used emogrifier so not sure.

Internally this library uses https://github.com/christiaan/InlineStyle which I haven't had an issue with so far, but my requirements have been pretty basic.
